name: Check

on:
  pull_request:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix build --out-link result-comfyui-frontend --quiet .#comfyui-frontend
      - run: nix store gc --quiet
      - run: nix build --out-link result-python3.pkgs.torch --quiet .#python3.pkgs.torch
      - run: nix store gc --quiet
      - run: nix flake check --quiet
