name: update

on:
  schedule:
    - cron: "20 2 * * *"

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - run: nix develop --command just up
      - name: Build comfyui-with-extensions if there are changes
        run: |
          if ! git diff --quiet; then
            nix develop --command just build comfyui-with-extensions
          fi
      - name: Build krita-ai-diffusion if there are changes
        run: |
          if ! git diff --quiet; then
            nix develop --command just build krita-ai-diffusion
          fi
      - name: Reformat, commit and push if there are changes
        run: |
          if ! git diff --quiet; then
            nix develop --command just fmt
            nix develop --command just check

            git config user.name "github-actions[bot]"
            git config user.email \
              "41898282+github-actions[bot]@users.noreply.github.com"

            git add .

            date="$(TZ=UTC date "+%FT%H:00:00Z")"
            GIT_COMMITTER_DATE="$date" GIT_AUTHOR_DATE="$date" \
              git commit --message "Update dependencies"

            git push
          fi
